name: buy_buy
description: "E-commerce app for online shopping"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  equatable: ^2.0.7
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  fonts:
    - family: MarkPro
      fonts:
        - asset: assets/fonts/markPro/FontFont_FF.Mark.Pro.Light.otf
          weight: 300
        - asset: assets/fonts/markPro/FontFont_FF.Mark.Pro.otf
          weight: 400
        - asset: assets/fonts/markPro/FontFont_FF.Mark.Pro.Bold.otf
          weight: 700
