// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHJqrug4gWE3NA85_mN1Ph6GTe2iP3QzQ',
    appId: '1:717637295963:web:f6810fbcc44588fa3b047e',
    messagingSenderId: '717637295963',
    projectId: 'tech-store-backend',
    authDomain: 'tech-store-backend.firebaseapp.com',
    storageBucket: 'tech-store-backend.firebasestorage.app',
    measurementId: 'G-M7MRHKZ7BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJroCL9jQrH5KO5HthPJvcGFtUhp9WRZ4',
    appId: '1:717637295963:android:ab6872b0152c33f63b047e',
    messagingSenderId: '717637295963',
    projectId: 'tech-store-backend',
    storageBucket: 'tech-store-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeCTwntbsuahh_0UUznfFdg5stawdpLA',
    appId: '1:717637295963:ios:55f2013628149f283b047e',
    messagingSenderId: '717637295963',
    projectId: 'tech-store-backend',
    storageBucket: 'tech-store-backend.firebasestorage.app',
    iosClientId: '717637295963-o8415cdg01knrgbie7mboovk0seom3ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.buybuy.buyBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeCTwntbsuahh_0UUznfFdg5stawdpLA',
    appId: '1:717637295963:ios:55f2013628149f283b047e',
    messagingSenderId: '717637295963',
    projectId: 'tech-store-backend',
    storageBucket: 'tech-store-backend.firebasestorage.app',
    iosClientId: '717637295963-o8415cdg01knrgbie7mboovk0seom3ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.buybuy.buyBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHJqrug4gWE3NA85_mN1Ph6GTe2iP3QzQ',
    appId: '1:717637295963:web:fcd12c703f38887b3b047e',
    messagingSenderId: '717637295963',
    projectId: 'tech-store-backend',
    authDomain: 'tech-store-backend.firebaseapp.com',
    storageBucket: 'tech-store-backend.firebasestorage.app',
    measurementId: 'G-CHQD6XJPT0',
  );
}